In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [2]:
df = pd.read_csv('tested_titanic.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [3]:
df.dropna(inplace=True)

In [4]:
df.head()

    Age  Pclass  SibSp  Parch  Survived
0  34.5       3      0      0         0
1  47.0       3      1      0         1
2  62.0       2      0      0         0
3  27.0       3      0      0         0
4  22.0       3      1      1         1

In [5]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [6]:
X.head()

    Age  Pclass  SibSp  Parch
0  34.5       3      0      0
1  47.0       3      1      0
2  62.0       2      0      0
3  27.0       3      0      0
4  22.0       3      1      1

In [7]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6238970588235293)

Applying Feature Construction

In [8]:
X['Family_size'] = X['SibSp'] + X['Parch'] + 1

In [9]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size
0  34.5       3      0      0            1
1  47.0       3      1      0            2
2  62.0       2      0      0            1
3  27.0       3      0      0            1
4  22.0       3      1      1            3

In [10]:
def myfunc(num):
    if num == 1:
        #alone
        return 0
    elif num >1 and num <=4:
        # small family
        return 1
    else:
        # large family
        return 2

In [11]:
myfunc(4)

1

In [12]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [13]:
X.head()

    Age  Pclass  SibSp  Parch  Family_size  Family_type
0  34.5       3      0      0            1            0
1  47.0       3      1      0            2            1
2  62.0       2      0      0            1            0
3  27.0       3      0      0            1            0
4  22.0       3      1      1            3            1

In [14]:
X.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [16]:
X.head()

    Age  Pclass  Family_type
0  34.5       3            0
1  47.0       3            1
2  62.0       2            0
3  27.0       3            0
4  22.0       3            1

In [17]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=20))

np.float64(0.6056985294117647)

Feature Splitting

In [18]:
df = pd.read_csv('tested_titanic.csv')

In [19]:
df['Name']

0                                  Kelly, Mr. James
1                  Wilkes, Mrs. James (Ellen Needs)
2                         Myles, Mr. Thomas Francis
3                                  Wirz, Mr. Albert
4      Hirvonen, Mrs. Alexander (Helga E Lindqvist)
                           ...
413                              Spector, Mr. Woolf
414                    Oliva y Ocana, Dona. Fermina
415                    Saether, Mr. Simon Sivertsen
416                             Ware, Mr. Frederick
417                        Peter, Master. Michael J
Name: Name, Length: 418, dtype: object

In [20]:
df['Title'] = df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [21]:
df['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

0          Mr
1         Mrs
2          Mr
3          Mr
4         Mrs
        ...
413        Mr
414      Dona
415        Mr
416        Mr
417    Master
Name: 0, Length: 418, dtype: object

In [22]:
df[['Title','Name']]

      Title                                          Name
0        Mr                              Kelly, Mr. James
1       Mrs              Wilkes, Mrs. James (Ellen Needs)
2        Mr                     Myles, Mr. Thomas Francis
3        Mr                              Wirz, Mr. Albert
4       Mrs  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
..      ...                                           ...
413      Mr                            Spector, Mr. Woolf
414    Dona                  Oliva y Ocana, Dona. Fermina
415      Mr                  Saether, Mr. Simon Sivertsen
416      Mr                           Ware, Mr. Frederick
417  Master                      Peter, Master. Michael J

[418 rows x 2 columns]

In [25]:
df.groupby('Title')[['Survived']].mean().sort_values(by='Survived', ascending=False)

        Survived
Title
Dona         1.0
Ms           1.0
Miss         1.0
Mrs          1.0
Col          0.0
Master       0.0
Dr           0.0
Mr           0.0
Rev          0.0

In [27]:
df['Is_Married'] = 0
df.loc[df['Title'] == 'Mrs', 'Is_Married'] = 1

In [28]:
df['Is_Married']

0      0
1      1
2      0
3      0
4      1
      ..
413    0
414    0
415    0
416    0
417    0
Name: Is_Married, Length: 418, dtype: int64

In [ ]:
import IPython

# 1. Automatically save the current notebook checkpoint
IPython.get_ipython().run_cell_magic('javascript', '', 'IPython.notebook.save_checkpoint();')

# 2. Add, commit, and push automatically to whichever repo you are in
!git add .
!git commit -m "Auto-update notebooks"
!git push origin main