In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.3'

In [4]:
sales = pd.Series([1,2,3])

In [5]:
sales

0    1
1    2
2    3
dtype: int64

In [6]:
sales[0:3]

0    1
1    2
2    3
dtype: int64

In [7]:
sales[2]

np.int64(3)

In [8]:
sales.index

RangeIndex(start=0, stop=3, step=1)

In [9]:
sales.values

array([1, 2, 3])

In [10]:
sales.dtype

dtype('int64')

In [11]:
sales.head()

0    1
1    2
2    3
dtype: int64

In [12]:
sales.tail(1)

2    3
dtype: int64

In [13]:
sales1 = pd.Series([1,2,7,8,9,4,5,3,4,5,3,6])

In [14]:
sales1.head()

0    1
1    2
2    7
3    8
4    9
dtype: int64

In [15]:
sales1.sort_values()

0     1
1     2
7     3
10    3
5     4
8     4
6     5
9     5
11    6
2     7
3     8
4     9
dtype: int64

In [16]:
sales1.isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
dtype: bool

In [17]:
sales1.count()

np.int64(12)

In [18]:
sales1 +1

0      2
1      3
2      8
3      9
4     10
5      5
6      6
7      4
8      5
9      6
10     4
11     7
dtype: int64

In [19]:
sales1*2

0      2
1      4
2     14
3     16
4     18
5      8
6     10
7      6
8      8
9     10
10     6
11    12
dtype: int64

In [20]:
sales1

0     1
1     2
2     7
3     8
4     9
5     4
6     5
7     3
8     4
9     5
10    3
11    6
dtype: int64

In [21]:
data = pd.DataFrame({
    'name' : ['anan','ben','forb'],
    'age' : [22,34,12]
})

In [22]:
data

   name  age
0  anan   22
1   ben   34
2  forb   12

In [23]:
data = pd.DataFrame({
    's' : sales, 's1' : sales1
})
data

      s  s1
0   1.0   1
1   2.0   2
2   3.0   7
3   NaN   8
4   NaN   9
5   NaN   4
6   NaN   5
7   NaN   3
8   NaN   4
9   NaN   5
10  NaN   3
11  NaN   6

In [24]:
data.s.isnull()

0     False
1     False
2     False
3      True
4      True
5      True
6      True
7      True
8      True
9      True
10     True
11     True
Name: s, dtype: bool

In [25]:
data.shape

(12, 2)

In [26]:
data.columns

Index(['s', 's1'], dtype='object')

In [27]:
data.s1.shape

(12,)

In [28]:
sales.shape

(3,)

In [29]:
data.loc[3,'s1']

np.int64(8)

In [30]:
data.iloc[3,1]

np.int64(8)

In [31]:
data.info

<bound method DataFrame.info of       s  s1
0   1.0   1
1   2.0   2
2   3.0   7
3   NaN   8
4   NaN   9
5   NaN   4
6   NaN   5
7   NaN   3
8   NaN   4
9   NaN   5
10  NaN   3
11  NaN   6>

In [32]:
data[data['s1']== 2]

     s  s1
1  2.0   2

In [33]:
multi_data = pd.DataFrame({
    'name' : ['dev','jay','mark','anna'],
    'park' : ['a','a','b','b'],
    'Lemonade' : [2,3,5,2]
}).set_index(['park','name'])

In [34]:
multi_data

           Lemonade
park name
a    dev          2
     jay          3
b    mark         5
     anna         2

In [35]:
multi_data.query('Lemonade>=3')

           Lemonade
park name
a    jay          3
b    mark         5

In [36]:
data.s1.drop_duplicates()

0     1
1     2
2     7
3     8
4     9
5     4
6     5
7     3
11    6
Name: s1, dtype: int64

In [37]:
data

      s  s1
0   1.0   1
1   2.0   2
2   3.0   7
3   NaN   8
4   NaN   9
5   NaN   4
6   NaN   5
7   NaN   3
8   NaN   4
9   NaN   5
10  NaN   3
11  NaN   6